name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20] # Test against multiple Node.js versions

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm" # Enable caching for faster dependency installation
      - name: Install Dependencies
        run: npm ci # Use npm ci for clean installs
      - name: Lint
        run: npm run lint # Add linting step
      - name: Build
        run: npm run build
      - name: Test
        run: npm run test # Add testing step
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        if: ${{ matrix.node-version == '18' }} # Only upload coverage from one node version
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Add codecov token as a secret
          files: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
